{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-1.3.0-beta02.aar",
          "url": "foundation-1.3.0-beta02.aar",
          "size": 3067170,
          "sha512": "d8cc291ee9f89ba9c5fd6d5e15af04ef5e0c298f0b6b274238eb47cec60c66274ddd8658596a9863594b985d88464828706c0241d2e0b2308dadea3deda843bb",
          "sha256": "57e7b6124baea70dac9aee766f5977ba911bfa3d84884ae3795b2df415f5f6d0",
          "sha1": "1acbb3d374e2b0a77c0007e31209dbaf684cd212",
          "md5": "8d7efc8da1bdbb850ef7aec2ccbf52e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-1.3.0-beta02.aar",
          "url": "foundation-1.3.0-beta02.aar",
          "size": 3067170,
          "sha512": "d8cc291ee9f89ba9c5fd6d5e15af04ef5e0c298f0b6b274238eb47cec60c66274ddd8658596a9863594b985d88464828706c0241d2e0b2308dadea3deda843bb",
          "sha256": "57e7b6124baea70dac9aee766f5977ba911bfa3d84884ae3795b2df415f5f6d0",
          "sha1": "1acbb3d374e2b0a77c0007e31209dbaf684cd212",
          "md5": "8d7efc8da1bdbb850ef7aec2ccbf52e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "foundation-1.3.0-beta02-sources.jar",
          "url": "foundation-1.3.0-beta02-sources.jar",
          "size": 418914,
          "sha512": "794356abf14144dd72485c5999f6656f443ac9816af2bcee99128bb3d715f6fdcb1fc58e005a08d9944a07986e6342db63cee9ff285249c1664e6c1d03ad1e38",
          "sha256": "7daac305eb0db9acf8f9255d9cfea810843c7e10f3c2cd1281fe1681390322cc",
          "sha1": "0599e5b72dc73cb5f667c1209ced19785b40f0a2",
          "md5": "851b598c0d0d823bd03c85316ab19327"
        }
      ]
    }
  ]
}