{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-unit",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.3.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.3.0-beta02.aar",
          "url": "ui-unit-1.3.0-beta02.aar",
          "size": 66779,
          "sha512": "c11283899a34aa07978c9c509aacc1df2f069908263b05bcb5ec5531438588840a2f3aa1432c2bc05229339b9ad476b74ab7adcaeb067ec7142aea9fc1d42dc1",
          "sha256": "d149d11dd79211c039dd002beb8a823107faed27e02e42823150177c05aa1aed",
          "sha1": "d0112b71f4340d017bf11274e361c201a1ae1e6f",
          "md5": "7350382b1046ac85a1b75d24b3d0ef99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.3.0-beta02.aar",
          "url": "ui-unit-1.3.0-beta02.aar",
          "size": 66779,
          "sha512": "c11283899a34aa07978c9c509aacc1df2f069908263b05bcb5ec5531438588840a2f3aa1432c2bc05229339b9ad476b74ab7adcaeb067ec7142aea9fc1d42dc1",
          "sha256": "d149d11dd79211c039dd002beb8a823107faed27e02e42823150177c05aa1aed",
          "sha1": "d0112b71f4340d017bf11274e361c201a1ae1e6f",
          "md5": "7350382b1046ac85a1b75d24b3d0ef99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-unit-1.3.0-beta02-sources.jar",
          "url": "ui-unit-1.3.0-beta02-sources.jar",
          "size": 24569,
          "sha512": "aa0a10c32c9400f834b03cfb97a977ed19c75227d79a9c888045f841731504d06fda00555b8796ebff6780657e30966bdbf454d4a4c4f76613b6434083241a0f",
          "sha256": "55955850f87ab0cedcdc224274b2896a86f9bfd82d99cf785e54e7bc13a51d79",
          "sha1": "e84197afacb3f5eb2861aab08f07d564ec55938e",
          "md5": "17cd73e38af95382b2b85c19a930def5"
        }
      ]
    }
  ]
}