{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.3.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.3.0-beta02.aar",
          "url": "ui-1.3.0-beta02.aar",
          "size": 4393325,
          "sha512": "6a088c1827040ce03e547abfd6339532166a93f514a72318182bf279bdd1b7e959dc64c8ffa41265e5cffbfacfc178220853a614884a2f24fbb74c6ad4e8f46a",
          "sha256": "7e288ccd9076ef57cd239da8f7f1b1aea544b80cdbdc3a808496bca6d8aeebe2",
          "sha1": "e5752e9058a4e24c5fbe5ff432ef310f65ad6fca",
          "md5": "d57008c1d0eeb5b0349877d46c88bf36"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview-poolingcontainer",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.3.0-beta02.aar",
          "url": "ui-1.3.0-beta02.aar",
          "size": 4393325,
          "sha512": "6a088c1827040ce03e547abfd6339532166a93f514a72318182bf279bdd1b7e959dc64c8ffa41265e5cffbfacfc178220853a614884a2f24fbb74c6ad4e8f46a",
          "sha256": "7e288ccd9076ef57cd239da8f7f1b1aea544b80cdbdc3a808496bca6d8aeebe2",
          "sha1": "e5752e9058a4e24c5fbe5ff432ef310f65ad6fca",
          "md5": "d57008c1d0eeb5b0349877d46c88bf36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-1.3.0-beta02-sources.jar",
          "url": "ui-1.3.0-beta02-sources.jar",
          "size": 567276,
          "sha512": "712fe139b3c5e1ea240061ac37a8c4112616aac4fc401508fb8c125a962c92478a15c9d901846653e42aa9c9f1dc84f92d2c6ec4c148df8baf01768b4a8ababd",
          "sha256": "50df05deaabddc7d7b389c339edc92d200c261c30d4070bf7e1622707f1f15ba",
          "sha1": "278b1f033a5bc2ecf0b9241b8a7fb0629b59d178",
          "md5": "a7941867f4f49f21e51cab39639846a7"
        }
      ]
    }
  ]
}