{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-text",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.3.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-1.3.0-beta02.aar",
          "url": "ui-text-1.3.0-beta02.aar",
          "size": 696654,
          "sha512": "2bb8851be1f7e4e91a39fd77592af982c301191135acc363365385bf221b0bc2f529821cd79bf918112553478d512aef14fcb93ffefba948a400fecec815486b",
          "sha256": "a3dba9f0e9bf5efcc883e115ec019b3a73e608dd722d30bf48d1074e21290e6c",
          "sha1": "57e7dcc26c57c8d00638189a8aab3639f5b79490",
          "md5": "4ff1ca852d9690f63be247331c1a4578"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-1.3.0-beta02.aar",
          "url": "ui-text-1.3.0-beta02.aar",
          "size": 696654,
          "sha512": "2bb8851be1f7e4e91a39fd77592af982c301191135acc363365385bf221b0bc2f529821cd79bf918112553478d512aef14fcb93ffefba948a400fecec815486b",
          "sha256": "a3dba9f0e9bf5efcc883e115ec019b3a73e608dd722d30bf48d1074e21290e6c",
          "sha1": "57e7dcc26c57c8d00638189a8aab3639f5b79490",
          "md5": "4ff1ca852d9690f63be247331c1a4578"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-text-1.3.0-beta02-sources.jar",
          "url": "ui-text-1.3.0-beta02-sources.jar",
          "size": 266966,
          "sha512": "02e8d37e2fd35224c4ec7b2578f320a047ca8fe9282e70ba802838163c2bfb087bf3e67ab5d58f2ab8ba68a0974d254a1e6eabc35ac16422638f463d0e98c0eb",
          "sha256": "937a1d3bbc890f2942cab16a9e854d2199c6a6042d3d639984482e9e33ec06a4",
          "sha1": "755f05d7f993160e60fc2c2d22bc7ff0bdd72e3d",
          "md5": "0dfc61320fa87be6273d90035fea8234"
        }
      ]
    }
  ]
}