{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.3.0-beta02.aar",
          "url": "runtime-1.3.0-beta02.aar",
          "size": 2074127,
          "sha512": "30f91ad5690ee195211ee594b87d68e28cd7120fd8bfc284657d8ca802313036777d73bde5e884a26d8f509e92dddf66e0589a707781c1c382bf82c796082430",
          "sha256": "8bce93c95eaa2b9004f6715d6579d0b9b284015de971008969fb322f07b6891d",
          "sha1": "9dd6f4871c4152e4052b0b1808bc283b33fc77a5",
          "md5": "c9943d9acfe23d31b0b99f8175c8a660"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.3.0-beta02.aar",
          "url": "runtime-1.3.0-beta02.aar",
          "size": 2074127,
          "sha512": "30f91ad5690ee195211ee594b87d68e28cd7120fd8bfc284657d8ca802313036777d73bde5e884a26d8f509e92dddf66e0589a707781c1c382bf82c796082430",
          "sha256": "8bce93c95eaa2b9004f6715d6579d0b9b284015de971008969fb322f07b6891d",
          "sha1": "9dd6f4871c4152e4052b0b1808bc283b33fc77a5",
          "md5": "c9943d9acfe23d31b0b99f8175c8a660"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-1.3.0-beta02-sources.jar",
          "url": "runtime-1.3.0-beta02-sources.jar",
          "size": 301943,
          "sha512": "4aa8dfb4f5b8e78b487c8eb79466c19c020e2ca2d261ec4190471cee4898501377189be1f2839e1b93230da91d69e8ed93a2611b5f10a4bcc1bed2bdbc749c21",
          "sha256": "a1b8062387e3e1a2d55943f8446ff37e1815d8a80fad864f8f2d206db5926ac9",
          "sha1": "8122d0bb2102db57d28b28d3117ceed59ad9df6f",
          "md5": "b0cbb538f692a3c3b70412b1b7ba30ea"
        }
      ]
    }
  ]
}