{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-tooling-preview",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-1.3.0-beta02.aar",
          "url": "ui-tooling-preview-1.3.0-beta02.aar",
          "size": 13174,
          "sha512": "211800050271c3f5dc43baea04cdd68e0c62161b2b90e8970f6d1a120708393530176234158bad0ac9302af845b986862b881cca10a2eaae94ac95cc64470f2f",
          "sha256": "25467cf0f65d22725319748bc8013a63fa59216267d47c3b3288c38fe2dbeb48",
          "sha1": "0124f15179facb4c3c4e663abd36f57f3fa14066",
          "md5": "ffedd5845c9212f691a934f85b9210a6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-1.3.0-beta02.aar",
          "url": "ui-tooling-preview-1.3.0-beta02.aar",
          "size": 13174,
          "sha512": "211800050271c3f5dc43baea04cdd68e0c62161b2b90e8970f6d1a120708393530176234158bad0ac9302af845b986862b881cca10a2eaae94ac95cc64470f2f",
          "sha256": "25467cf0f65d22725319748bc8013a63fa59216267d47c3b3288c38fe2dbeb48",
          "sha1": "0124f15179facb4c3c4e663abd36f57f3fa14066",
          "md5": "ffedd5845c9212f691a934f85b9210a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooling-preview-1.3.0-beta02-sources.jar",
          "url": "ui-tooling-preview-1.3.0-beta02-sources.jar",
          "size": 8239,
          "sha512": "2795ac4812692f0bb675e4060213fc3a89034fdb2c6e1550b82f1971b808d432fdda4c824498ca2ce2d325b82afbe635b3466e3c5d6a5a408f0c48626eaa98e2",
          "sha256": "a651ab0ce34d8f89f8f34b969ea26c82c8ce43bc00c79415fa790e3d5ef899f1",
          "sha1": "8432308a1cb0e2db5ff0f8ff31398f5293b22573",
          "md5": "6ab2ee3958d14aaa72cdc53fec530d03"
        }
      ]
    }
  ]
}