{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stripe",
    "module": "stripe-3ds2-android",
    "version": "6.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "stripe-3ds2-android-6.1.5.aar",
          "url": "stripe-3ds2-android-6.1.5.aar",
          "size": 647317,
          "sha512": "85cffaed576c4e9f7590004bcd7392a17600a41988b8e6d0ceab200d06dcff8e89cda17d05176677459d5f2c6d6eacc04fd60d45ddf0485696711072dc14a5cd",
          "sha256": "31648f9e9161f9a6d9795fb024306c47c8134ef086fa6f01a4264bdda21c742f",
          "sha1": "74f145862674d9d9b81b6bd09e8982fcd5354e9e",
          "md5": "99232169a8a7947a5ca84cf804d18ec1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.69"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.21"
          }
        }
      ],
      "files": [
        {
          "name": "stripe-3ds2-android-6.1.5.aar",
          "url": "stripe-3ds2-android-6.1.5.aar",
          "size": 647317,
          "sha512": "85cffaed576c4e9f7590004bcd7392a17600a41988b8e6d0ceab200d06dcff8e89cda17d05176677459d5f2c6d6eacc04fd60d45ddf0485696711072dc14a5cd",
          "sha256": "31648f9e9161f9a6d9795fb024306c47c8134ef086fa6f01a4264bdda21c742f",
          "sha1": "74f145862674d9d9b81b6bd09e8982fcd5354e9e",
          "md5": "99232169a8a7947a5ca84cf804d18ec1"
        }
      ]
    }
  ]
}
