{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.webkit",
    "module": "webkit",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "7016559"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webkit-1.4.0.aar",
          "url": "webkit-1.4.0.aar",
          "size": 101702,
          "sha512": "773ef9216f96b310255dfe7a2a9af9db2528b6d0842c686e22918e0df513e7553fa53ecd14b153b811b50252b9b8ddd703fa21c218138a9b5f5e9de68522d437",
          "sha256": "1a11b20aac1352de72da5366b76682ce8ba6b9b0bef16a76bb3df41a9db89197",
          "sha1": "48e4cd9c63f7dc9fc62631d8dfbb77e890b459aa",
          "md5": "a179f9b30b6b2ae4153720eb12074472"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webkit-1.4.0.aar",
          "url": "webkit-1.4.0.aar",
          "size": 101702,
          "sha512": "773ef9216f96b310255dfe7a2a9af9db2528b6d0842c686e22918e0df513e7553fa53ecd14b153b811b50252b9b8ddd703fa21c218138a9b5f5e9de68522d437",
          "sha256": "1a11b20aac1352de72da5366b76682ce8ba6b9b0bef16a76bb3df41a9db89197",
          "sha1": "48e4cd9c63f7dc9fc62631d8dfbb77e890b459aa",
          "md5": "a179f9b30b6b2ae4153720eb12074472"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webkit-1.4.0-sources.jar",
          "url": "webkit-1.4.0-sources.jar",
          "size": 119309,
          "sha512": "ba4a20a65913ffc5616178bcedf8f216e7bd6214e57cbae95996488e24cde045acb4944afcff787fce0486992e59192e4b28923b4c6a595d1c252dbb4835cf7c",
          "sha256": "f0b232f6a907cae8f574301a18eb197002dd976d918afa4d1db036c8fc424277",
          "sha1": "a73605771c2a3ea2e168fa93ece88975d67587a9",
          "md5": "3545e967ca869019fdc92d317b969710"
        }
      ]
    }
  ]
}
