{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-graphics",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.3.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.3.0-beta02.aar",
          "url": "ui-graphics-1.3.0-beta02.aar",
          "size": 1408450,
          "sha512": "7e61d0a06b42ef7b77721b6a90ffd8b0a9d18fae1d668b31aec12b0d0b2a7e26813d6f4344cdd2ea182725668a18893bfcd2ad0691f470d54c5f8c311850d7ba",
          "sha256": "614f3079944d3b3381c5c54486dd18be2ce113b10296630c63baf20e0150944d",
          "sha1": "39588a03cae42848dc9def0dd2c333521329fcb6",
          "md5": "394ddfedf2cd6e165d6f3f9bedea5953"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.3.0-beta02.aar",
          "url": "ui-graphics-1.3.0-beta02.aar",
          "size": 1408450,
          "sha512": "7e61d0a06b42ef7b77721b6a90ffd8b0a9d18fae1d668b31aec12b0d0b2a7e26813d6f4344cdd2ea182725668a18893bfcd2ad0691f470d54c5f8c311850d7ba",
          "sha256": "614f3079944d3b3381c5c54486dd18be2ce113b10296630c63baf20e0150944d",
          "sha1": "39588a03cae42848dc9def0dd2c333521329fcb6",
          "md5": "394ddfedf2cd6e165d6f3f9bedea5953"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-graphics-1.3.0-beta02-sources.jar",
          "url": "ui-graphics-1.3.0-beta02-sources.jar",
          "size": 160453,
          "sha512": "4382c83264be466f6930ab334910b21d97d6c161aa45d56c83d2cc4e4ef0e6ddd69ce558670e3f0ea3d71bb78dc949e304069530ab90f52eff7e2eb0fc905052",
          "sha256": "f7c003a8a24e8f2c0216446baed5c5279a831f968cb2978500f9cf16b2625ff7",
          "sha1": "01f0725b5ccc7b14a306c879122268e7c236dc2c",
          "md5": "aebb2b7ef4b39a3d9a01b91a947ee22a"
        }
      ]
    }
  ]
}