{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-1.3.0-beta02.aar",
          "url": "material-ripple-1.3.0-beta02.aar",
          "size": 73457,
          "sha512": "0e79dbdca035cc40abbbe0310404426763569856474a3232c59395e79bb7a02f1c026ccd48e884b58f80d2484bbe2e38fc87f63ee378b0fb5f2e8858df338af2",
          "sha256": "e9f64a2d326ae9ccd7794495a13cd298a2353dd1c0d1f61abe8c0bb592ec72b5",
          "sha1": "02fc6d8ccbf3961936eff9e6c95614458bb787f3",
          "md5": "6fc40355432df0aefdd22171310de310"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-1.3.0-beta02.aar",
          "url": "material-ripple-1.3.0-beta02.aar",
          "size": 73457,
          "sha512": "0e79dbdca035cc40abbbe0310404426763569856474a3232c59395e79bb7a02f1c026ccd48e884b58f80d2484bbe2e38fc87f63ee378b0fb5f2e8858df338af2",
          "sha256": "e9f64a2d326ae9ccd7794495a13cd298a2353dd1c0d1f61abe8c0bb592ec72b5",
          "sha1": "02fc6d8ccbf3961936eff9e6c95614458bb787f3",
          "md5": "6fc40355432df0aefdd22171310de310"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-ripple-1.3.0-beta02-sources.jar",
          "url": "material-ripple-1.3.0-beta02-sources.jar",
          "size": 21691,
          "sha512": "1b90df22733378bbf14bf73f1e44954476a67b9fbd22ad2d14e57f4970e2c06bc85a1a70d4b9ae85b83e7eb760ce9ba9fc13a5c61f68ce60afb64335b97022fa",
          "sha256": "ed1dc4e848d69095c883c2e02a0794f0adf34b021762895f5ac010dc74a67e15",
          "sha1": "17dc970b3b9979e18c1401c0d30c381a1d4eeff1",
          "md5": "3829807753b151eda51c1840b346b97e"
        }
      ]
    }
  ]
}