{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-compose",
    "version": "2.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.5.2.aar",
          "url": "navigation-compose-2.5.2.aar",
          "size": 1095739,
          "sha512": "c895472ecec838c687c628d4554e0893a7c70c28e81e02b55950b144b089e10df256ad9c6270574b80b943fe28d6c768ae8550110063a64ee06dc557423a48a7",
          "sha256": "5a57c79baaa6f317f55700ef39aae8a412f8fc6b2239913ee2fdc876af1f409a",
          "sha1": "fb407cd07ca47a182f70577af621b51589044c45",
          "md5": "c2047cadba23dca2fc651ecf917c8fcb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.5.2.aar",
          "url": "navigation-compose-2.5.2.aar",
          "size": 1095739,
          "sha512": "c895472ecec838c687c628d4554e0893a7c70c28e81e02b55950b144b089e10df256ad9c6270574b80b943fe28d6c768ae8550110063a64ee06dc557423a48a7",
          "sha256": "5a57c79baaa6f317f55700ef39aae8a412f8fc6b2239913ee2fdc876af1f409a",
          "sha1": "fb407cd07ca47a182f70577af621b51589044c45",
          "md5": "c2047cadba23dca2fc651ecf917c8fcb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-compose-2.5.2-sources.jar",
          "url": "navigation-compose-2.5.2-sources.jar",
          "size": 10998,
          "sha512": "74fc7e04fe39d90cfc265654cc0b55b20f1ab3d80ab4ad81d58729cf937188a1cd9dc3e8bb53dc054ec61333406354acb7e3d42e4281e2c082e57a37cb749f06",
          "sha256": "f91b4a3ccd95974562d6b56004310e4d32ce2f107f302e815a73ea41da4601d6",
          "sha1": "8b1dd15fa0586e9f0850d9a3e3ece7bec443a75a",
          "md5": "8db21b74d722c7d7e7c866b240daa1cf"
        }
      ]
    }
  ]
}