{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.fresco",
    "module": "animated-gif",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "animated-gif-2.5.0.aar",
          "url": "animated-gif-2.5.0.aar",
          "size": 343601,
          "sha512": "a6c19db14f50acf5242329f3c425586bcd2207c007ea0cec298808f30b6357c28a02ca2ce45c65ac6d7f5347de5a4d4153e2a61375e527d6c841d174c680d15e",
          "sha256": "c465cc5993e8233c39ddc5e32fdd2f316ab82f524a5fe0e5c458e142804671b8",
          "sha1": "f08f7ad3abf216f674b636176d45d59fd503d19b",
          "md5": "316f5762c88bf38868a5d201836c8713"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.parse.bolts",
          "module": "bolts-tasks",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "nativeloader",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fbcore",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "animated-base",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "animated-gif-2.5.0.aar",
          "url": "animated-gif-2.5.0.aar",
          "size": 343601,
          "sha512": "a6c19db14f50acf5242329f3c425586bcd2207c007ea0cec298808f30b6357c28a02ca2ce45c65ac6d7f5347de5a4d4153e2a61375e527d6c841d174c680d15e",
          "sha256": "c465cc5993e8233c39ddc5e32fdd2f316ab82f524a5fe0e5c458e142804671b8",
          "sha1": "f08f7ad3abf216f674b636176d45d59fd503d19b",
          "md5": "316f5762c88bf38868a5d201836c8713"
        }
      ]
    }
  ]
}
