{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-core",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-1.3.0-beta02.aar",
          "url": "material-icons-core-1.3.0-beta02.aar",
          "size": 687932,
          "sha512": "d136a9842707afcb9d840d1eba82d1b5930493297801b28862dd053957ff4d0979a2ae7a803cd504c913f225e75591515b0d78d49e3bf1794d7fb6e910fe5fc8",
          "sha256": "47dd70ec48c6d0f558b26de2ce661f7808c0fd7b30034afdfdbf2e9612c263fd",
          "sha1": "fb68241804553260835470228fd27b01d6e7f89c",
          "md5": "61a43d8306b8db001bcedff8ba34311b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-1.3.0-beta02.aar",
          "url": "material-icons-core-1.3.0-beta02.aar",
          "size": 687932,
          "sha512": "d136a9842707afcb9d840d1eba82d1b5930493297801b28862dd053957ff4d0979a2ae7a803cd504c913f225e75591515b0d78d49e3bf1794d7fb6e910fe5fc8",
          "sha256": "47dd70ec48c6d0f558b26de2ce661f7808c0fd7b30034afdfdbf2e9612c263fd",
          "sha1": "fb68241804553260835470228fd27b01d6e7f89c",
          "md5": "61a43d8306b8db001bcedff8ba34311b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-icons-core-1.3.0-beta02-sources.jar",
          "url": "material-icons-core-1.3.0-beta02-sources.jar",
          "size": 239750,
          "sha512": "7ac93a8bdba04466ec7347276f5119feceb9d032c496a5d0e0da3e3d19938dcbce37e4acff82cda12fd495bea1f380c0e723420281e33e4e35be39e69cf503d0",
          "sha256": "92d9208e2dcad1d6d9e50b455a44aae640f0aaebff178d7da4eacca0699a0f3e",
          "sha1": "6f8c0161762a875d864897b47e60505a6d023606",
          "md5": "3e84589020b3d04aa17fd6bbeb045d0b"
        }
      ]
    }
  ]
}