{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-util",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-util-1.3.0-beta02.aar",
          "url": "ui-util-1.3.0-beta02.aar",
          "size": 8630,
          "sha512": "aa4d417b95f120edf68444a1225410ff55adf35c4a4dfdb6c4c7eec17de7893824a0da054a50d223bfac05690eb0685e9d9f5dddab6c9ff7d3935d536fb127a8",
          "sha256": "0c3ac3b0e80f842f491b6256a045ebbce0be87aef642759e6579db91b07deefb",
          "sha1": "73be6bded988ff6280165bae2ec86e15229d3564",
          "md5": "8178cc07f273c458855b2c2731fe1dea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-1.3.0-beta02.aar",
          "url": "ui-util-1.3.0-beta02.aar",
          "size": 8630,
          "sha512": "aa4d417b95f120edf68444a1225410ff55adf35c4a4dfdb6c4c7eec17de7893824a0da054a50d223bfac05690eb0685e9d9f5dddab6c9ff7d3935d536fb127a8",
          "sha256": "0c3ac3b0e80f842f491b6256a045ebbce0be87aef642759e6579db91b07deefb",
          "sha1": "73be6bded988ff6280165bae2ec86e15229d3564",
          "md5": "8178cc07f273c458855b2c2731fe1dea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-util-1.3.0-beta02-sources.jar",
          "url": "ui-util-1.3.0-beta02-sources.jar",
          "size": 4754,
          "sha512": "55fad605edb6562f2ffef78e9a21ec241c437d57c6118fcc3804b65eeabddf47352c5d06c4115094233dc01159313db60d398d18fbe462af4929b1971608f9df",
          "sha256": "6937ed4605bb25aa4ebe2e5bf54301f5f587b4b357dd8a864e1f6ff9d0be6c41",
          "sha1": "6452653a0f6ac6d57e95c11526e9f1c6b4733569",
          "md5": "26018006a0fdf41321089a266bec5ed5"
        }
      ]
    }
  ]
}