{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.3.0-beta02.aar",
          "url": "material-1.3.0-beta02.aar",
          "size": 2643241,
          "sha512": "756e1f8ef6b4be5edf336dc163087b5661a6c36c28deba24fb51a867db845ab1137ff6ae51824beff0ab25f71230a001b36c1388e41aeb3f856a9641809bc9ee",
          "sha256": "a2a969c1d08e50fe2dff36c55b09d81cea022072be6039864edc00c878cca29b",
          "sha1": "fb7a217326b825835a0a4e31b31b8183a22c0cdc",
          "md5": "97bb842753a7d617fc00cebfeea9bcec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.3.0-beta02.aar",
          "url": "material-1.3.0-beta02.aar",
          "size": 2643241,
          "sha512": "756e1f8ef6b4be5edf336dc163087b5661a6c36c28deba24fb51a867db845ab1137ff6ae51824beff0ab25f71230a001b36c1388e41aeb3f856a9641809bc9ee",
          "sha256": "a2a969c1d08e50fe2dff36c55b09d81cea022072be6039864edc00c878cca29b",
          "sha1": "fb7a217326b825835a0a4e31b31b8183a22c0cdc",
          "md5": "97bb842753a7d617fc00cebfeea9bcec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-1.3.0-beta02-sources.jar",
          "url": "material-1.3.0-beta02-sources.jar",
          "size": 203570,
          "sha512": "47ae91f34138552438da1a8df2a3e21acfe28b4681b98b8b2594985b2e31f5efe9c0150d1dd8267ad1e6e5ce36068e8e8e727472c89571ddc4de6024a73eb766",
          "sha256": "b5e291a105f976b73247680866ac561ad5f289664d504ab65b0355a9f42f0601",
          "sha1": "926ca91741133d388108469cc053668603544906",
          "md5": "e0395b5ef03e33b2302c6655dfeda43b"
        }
      ]
    }
  ]
}