{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-livedata",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-1.3.0-beta02.aar",
          "url": "runtime-livedata-1.3.0-beta02.aar",
          "size": 7562,
          "sha512": "35f9a78fe0557aca02ab9405910c9508c7dd98a6276e1712771e99aef80efc7b83e9241a4af414763f9ff3cd832dd34015d7aac0e062e26d39713de31be22639",
          "sha256": "8a961abf412168358d909c2a7add7fc61974968f5895bfd525f15be850d701e6",
          "sha1": "699cb5d55fe3819c1f8afcd72cae3e9340819d6b",
          "md5": "0a583fb8e9906702f2c1dbae4c9fbe1c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-1.3.0-beta02.aar",
          "url": "runtime-livedata-1.3.0-beta02.aar",
          "size": 7562,
          "sha512": "35f9a78fe0557aca02ab9405910c9508c7dd98a6276e1712771e99aef80efc7b83e9241a4af414763f9ff3cd832dd34015d7aac0e062e26d39713de31be22639",
          "sha256": "8a961abf412168358d909c2a7add7fc61974968f5895bfd525f15be850d701e6",
          "sha1": "699cb5d55fe3819c1f8afcd72cae3e9340819d6b",
          "md5": "0a583fb8e9906702f2c1dbae4c9fbe1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-livedata-1.3.0-beta02-sources.jar",
          "url": "runtime-livedata-1.3.0-beta02-sources.jar",
          "size": 1824,
          "sha512": "12fdf7b2e70e16d3bcb59966d8e05b36b9698923cb467e376ee542aa1c98f87996f1b204a688dd2f783701a67055260ab797b6bc70e046df095bb535c7d505a2",
          "sha256": "2940823fd4f14afcab6a5aa9ad79f2a353f78c1312f9251fdd7c017ad171cff9",
          "sha1": "a36eb1d628eb1d76e540e9357a1330ade67e328c",
          "md5": "9900ddee4f1294723a75e9a0837241e3"
        }
      ]
    }
  ]
}