{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.security",
    "module": "security-crypto",
    "version": "1.1.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "6994272"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "security-crypto-1.1.0-alpha03.aar",
          "url": "security-crypto-1.1.0-alpha03.aar",
          "size": 27183,
          "sha512": "55bb7ea5c633f668881c88be370eaf26f2086a983cac3fa818be6884e8a791cb12b1e5c7c39af6c024062bf3bea6be034f0a42d5ea7d19522f68cdd42c6a055c",
          "sha256": "52a9566768d047928978841337d4607109bb1e81801315f86237478621475073",
          "sha1": "f54110eab7610d08d7c41c594b3a248dac488e00",
          "md5": "fbaea9a90a4a480d216fb6f4c5281956"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "security-crypto-1.1.0-alpha03.aar",
          "url": "security-crypto-1.1.0-alpha03.aar",
          "size": 27183,
          "sha512": "55bb7ea5c633f668881c88be370eaf26f2086a983cac3fa818be6884e8a791cb12b1e5c7c39af6c024062bf3bea6be034f0a42d5ea7d19522f68cdd42c6a055c",
          "sha256": "52a9566768d047928978841337d4607109bb1e81801315f86237478621475073",
          "sha1": "f54110eab7610d08d7c41c594b3a248dac488e00",
          "md5": "fbaea9a90a4a480d216fb6f4c5281956"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-crypto-1.1.0-alpha03-sources.jar",
          "url": "security-crypto-1.1.0-alpha03-sources.jar",
          "size": 14420,
          "sha512": "34b53604ba613fd9a0771bb536442b06ad7ecf281e3b7ac60a49596d5b94b430c43fc2376c130aac63c60cd6a103eb3e5a317fc1eaafb9d79edb288c20566c39",
          "sha256": "79e3f20be9c8ea90c47aa98a6e69740cd1e6f3a2a4eb5dffb865b4ea75acb511",
          "sha1": "a96855861b33f9a46ca6a1556118ae592cad2014",
          "md5": "ed485895691ed033ebcb614ca10acd01"
        }
      ]
    }
  ]
}
