{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-test",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6n3wvvyeubbytcxzxjyk33a5eq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-test-metadata-1.6.0-all.jar",
          "url": "kotlinx-coroutines-test-1.6.0-all.jar",
          "size": 13117,
          "sha512": "1eac209ebf3ddcf267f8c8b198a7f5ec7a40a0b4181f660a60cd1e57fad99976ea7d5a0a5c2b564af32070a7ff2a820ad5394e21bb4cf788aa667409117b4556",
          "sha256": "d4c4022c8e083edb379ed920011e2d82d7539538582b91ead0b3cfc4072a53c3",
          "sha1": "1959dba2dc7a4469d9f875d245e6ec24b32d8bfa",
          "md5": "7a8fe3bbb7917e6a321d15589feb9913"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-test-1.6.0.jar",
          "url": "kotlinx-coroutines-test-1.6.0.jar",
          "size": 11747,
          "sha512": "7b6d638dc0aa77bcdba7ab7e1d22113b700e767f97de222061b6c9b2ec044e1a3bd3c240607d79ae019a03e4a9b88c5f86adfbc11dd484388368e4137b3a161f",
          "sha256": "7de54139ef9fff52f58287c98bb62968978ddfa008cca762bfe2b080a43621e7",
          "sha1": "18e38f3934a730d212690a34cabfb687ab1d4a57",
          "md5": "167d29c43447891cbb665170cf14537f"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosarm32/1.6.0/kotlinx-coroutines-test-iosarm32-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosarm32",
        "version": "1.6.0"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosarm32/1.6.0/kotlinx-coroutines-test-iosarm32-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosarm32",
        "version": "1.6.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosarm64/1.6.0/kotlinx-coroutines-test-iosarm64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosarm64",
        "version": "1.6.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosarm64/1.6.0/kotlinx-coroutines-test-iosarm64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosarm64",
        "version": "1.6.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iossimulatorarm64/1.6.0/kotlinx-coroutines-test-iossimulatorarm64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iossimulatorarm64",
        "version": "1.6.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iossimulatorarm64/1.6.0/kotlinx-coroutines-test-iossimulatorarm64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iossimulatorarm64",
        "version": "1.6.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosx64/1.6.0/kotlinx-coroutines-test-iosx64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosx64",
        "version": "1.6.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosx64/1.6.0/kotlinx-coroutines-test-iosx64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosx64",
        "version": "1.6.0"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-js/1.6.0/kotlinx-coroutines-test-js-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-js",
        "version": "1.6.0"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-js/1.6.0/kotlinx-coroutines-test-js-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-js",
        "version": "1.6.0"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-js/1.6.0/kotlinx-coroutines-test-js-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-js",
        "version": "1.6.0"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-js/1.6.0/kotlinx-coroutines-test-js-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-js",
        "version": "1.6.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-jvm/1.6.0/kotlinx-coroutines-test-jvm-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-jvm",
        "version": "1.6.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-jvm/1.6.0/kotlinx-coroutines-test-jvm-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-jvm",
        "version": "1.6.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-linuxx64/1.6.0/kotlinx-coroutines-test-linuxx64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-linuxx64",
        "version": "1.6.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-macosarm64/1.6.0/kotlinx-coroutines-test-macosarm64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-macosarm64",
        "version": "1.6.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-macosarm64/1.6.0/kotlinx-coroutines-test-macosarm64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-macosarm64",
        "version": "1.6.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-macosx64/1.6.0/kotlinx-coroutines-test-macosx64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-macosx64",
        "version": "1.6.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-macosx64/1.6.0/kotlinx-coroutines-test-macosx64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-macosx64",
        "version": "1.6.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-mingwx64/1.6.0/kotlinx-coroutines-test-mingwx64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-mingwx64",
        "version": "1.6.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvosarm64/1.6.0/kotlinx-coroutines-test-tvosarm64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvosarm64",
        "version": "1.6.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvosarm64/1.6.0/kotlinx-coroutines-test-tvosarm64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvosarm64",
        "version": "1.6.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvossimulatorarm64/1.6.0/kotlinx-coroutines-test-tvossimulatorarm64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvossimulatorarm64",
        "version": "1.6.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvossimulatorarm64/1.6.0/kotlinx-coroutines-test-tvossimulatorarm64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvossimulatorarm64",
        "version": "1.6.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvosx64/1.6.0/kotlinx-coroutines-test-tvosx64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvosx64",
        "version": "1.6.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvosx64/1.6.0/kotlinx-coroutines-test-tvosx64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvosx64",
        "version": "1.6.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosarm32/1.6.0/kotlinx-coroutines-test-watchosarm32-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosarm32",
        "version": "1.6.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosarm32/1.6.0/kotlinx-coroutines-test-watchosarm32-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosarm32",
        "version": "1.6.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosarm64/1.6.0/kotlinx-coroutines-test-watchosarm64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosarm64",
        "version": "1.6.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosarm64/1.6.0/kotlinx-coroutines-test-watchosarm64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosarm64",
        "version": "1.6.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchossimulatorarm64/1.6.0/kotlinx-coroutines-test-watchossimulatorarm64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchossimulatorarm64",
        "version": "1.6.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchossimulatorarm64/1.6.0/kotlinx-coroutines-test-watchossimulatorarm64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchossimulatorarm64",
        "version": "1.6.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosx64/1.6.0/kotlinx-coroutines-test-watchosx64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosx64",
        "version": "1.6.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosx64/1.6.0/kotlinx-coroutines-test-watchosx64-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosx64",
        "version": "1.6.0"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosx86/1.6.0/kotlinx-coroutines-test-watchosx86-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosx86",
        "version": "1.6.0"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosx86/1.6.0/kotlinx-coroutines-test-watchosx86-1.6.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosx86",
        "version": "1.6.0"
      }
    }
  ]
}
