{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.0.2"
    }
  },
  "component" : {
    "group" : "com.github.CanHub",
    "module" : "Android-Image-Cropper",
    "version" : "4.3.0",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "releaseApiPublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-api"
    },
    "dependencies" : [ {
      "group" : "androidx.databinding",
      "module" : "viewbinding",
      "version" : {
        "requires" : "7.0.0"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib-jdk8",
      "version" : {
        "requires" : "1.5.20"
      }
    } ],
    "files" : [ {
      "name" : "Android-Image-Cropper-4.3.0.aar",
      "url" : "Android-Image-Cropper-4.3.0.aar",
      "size" : 212339,
      "sha512" : "bd16d413ce37be028664cd81dccb473c371f236523fbde6ce36d275455874f405a83013d3248fb4bd623e666cbd16d704c3190eb167a2ae7783ddfd021e413b3",
      "sha256" : "f96f93b98d58b75e0d9d667c4e959b2b1fbc6ee06f4d7b7d15cef4c083ae8b62",
      "sha1" : "674462cc1bbbf5807dc804ebbade42fcffdf0e18",
      "md5" : "9b3b6e80c747bc1d6f3f1e259b7c8e31"
    } ]
  }, {
    "name" : "releaseRuntimePublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-parcelize-runtime",
      "version" : {
        "requires" : "1.5.20"
      }
    }, {
      "group" : "androidx.databinding",
      "module" : "viewbinding",
      "version" : {
        "requires" : "7.0.0"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib-jdk8",
      "version" : {
        "requires" : "1.5.20"
      }
    }, {
      "group" : "androidx.appcompat",
      "module" : "appcompat",
      "version" : {
        "requires" : "1.3.1"
      }
    }, {
      "group" : "androidx.activity",
      "module" : "activity-ktx",
      "version" : {
        "requires" : "1.3.1"
      }
    }, {
      "group" : "androidx.exifinterface",
      "module" : "exifinterface",
      "version" : {
        "requires" : "1.3.3"
      }
    }, {
      "group" : "androidx.core",
      "module" : "core-ktx",
      "version" : {
        "requires" : "1.6.0"
      }
    }, {
      "group" : "org.jetbrains.kotlinx",
      "module" : "kotlinx-coroutines-core",
      "version" : {
        "requires" : "1.5.1"
      }
    }, {
      "group" : "org.jetbrains.kotlinx",
      "module" : "kotlinx-coroutines-android",
      "version" : {
        "requires" : "1.5.1"
      }
    } ],
    "files" : [ {
      "name" : "Android-Image-Cropper-4.3.0.aar",
      "url" : "Android-Image-Cropper-4.3.0.aar",
      "size" : 212339,
      "sha512" : "bd16d413ce37be028664cd81dccb473c371f236523fbde6ce36d275455874f405a83013d3248fb4bd623e666cbd16d704c3190eb167a2ae7783ddfd021e413b3",
      "sha256" : "f96f93b98d58b75e0d9d667c4e959b2b1fbc6ee06f4d7b7d15cef4c083ae8b62",
      "sha1" : "674462cc1bbbf5807dc804ebbade42fcffdf0e18",
      "md5" : "9b3b6e80c747bc1d6f3f1e259b7c8e31"
    } ]
  } ]
}