{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-layout",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-1.3.0-beta02.aar",
          "url": "foundation-layout-1.3.0-beta02.aar",
          "size": 474139,
          "sha512": "3bf77b491d92b667223ef048d4b6900bbf2d2f91ce3bbe866cc892e9485e173c56d5fa1aa4d8f8851d750c480676f25474341b841bc588408b779224c73d5091",
          "sha256": "8fc67b9d718b7c27a677334c2c1b994d425f437f12eef0adec5d65c1b8f2bc2b",
          "sha1": "4156f8b8a2b3fe95ecc6ce41dd84f9da7a6590a1",
          "md5": "5e2a94011abead0fce79b6b2009b8e28"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-1.3.0-beta02.aar",
          "url": "foundation-layout-1.3.0-beta02.aar",
          "size": 474139,
          "sha512": "3bf77b491d92b667223ef048d4b6900bbf2d2f91ce3bbe866cc892e9485e173c56d5fa1aa4d8f8851d750c480676f25474341b841bc588408b779224c73d5091",
          "sha256": "8fc67b9d718b7c27a677334c2c1b994d425f437f12eef0adec5d65c1b8f2bc2b",
          "sha1": "4156f8b8a2b3fe95ecc6ce41dd84f9da7a6590a1",
          "md5": "5e2a94011abead0fce79b6b2009b8e28"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "foundation-layout-1.3.0-beta02-sources.jar",
          "url": "foundation-layout-1.3.0-beta02-sources.jar",
          "size": 65737,
          "sha512": "9279b97c790a5dc9d938911962a3a32edcb84b274a352926043e7fcaf9d05481d369708ac5d5f58367e63051cea6dfe4d062fcc8f077a7e47db5b2310ad6164d",
          "sha256": "b1e76b74b9214fb089d776f1825bc175b94606438cc65252503a8fa6d3135686",
          "sha1": "39b35a7d0e3bb437de349ebca059b318b51bd770",
          "md5": "eef633c71a60dfbe2ec572eecb0fff84"
        }
      ]
    }
  ]
}