{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-geometry",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-1.3.0-beta02.aar",
          "url": "ui-geometry-1.3.0-beta02.aar",
          "size": 37864,
          "sha512": "6ee9ad1090b884162f5d6609b84e0dda272e5ef7db8752ec60851d27123e55475081a79b8f478c0a2aae091161cbf92100b896f33caad271cd13a6b72ad5c911",
          "sha256": "1db2296d9ee152d0d96787230cac439595a5d25b67f7d77843a6b5b559382443",
          "sha1": "d38e0aefd085584082643de015e0c068cdffaaab",
          "md5": "f42103cb80b5d6b11b4a7d2a909fd165"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-1.3.0-beta02.aar",
          "url": "ui-geometry-1.3.0-beta02.aar",
          "size": 37864,
          "sha512": "6ee9ad1090b884162f5d6609b84e0dda272e5ef7db8752ec60851d27123e55475081a79b8f478c0a2aae091161cbf92100b896f33caad271cd13a6b72ad5c911",
          "sha256": "1db2296d9ee152d0d96787230cac439595a5d25b67f7d77843a6b5b559382443",
          "sha1": "d38e0aefd085584082643de015e0c068cdffaaab",
          "md5": "f42103cb80b5d6b11b4a7d2a909fd165"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-geometry-1.3.0-beta02-sources.jar",
          "url": "ui-geometry-1.3.0-beta02-sources.jar",
          "size": 17888,
          "sha512": "2e0bea8364ccf5a69d760251e6d537100b876766f00bc6a6e57bb58ba429e1359785ddb0b436322196bbe55799deb864b2e62824149bd027bc1ddaa4bbf7e34f",
          "sha256": "0e5663e975d3d06f883e78caf7099742b7395f62ca91987b056c3fca56b34960",
          "sha1": "11f1b168bb58fbf1227ecedfc05a81ad37ef67e9",
          "md5": "5e3e2db960d5621e0c70393d9e649f74"
        }
      ]
    }
  ]
}