{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-testing",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "room-testing-2.4.2.aar",
          "url": "room-testing-2.4.2.aar",
          "size": 13623,
          "sha512": "049629bb0a821cb5278a4cfcd66110416f67e9eeeae25315857be33000c2681ee09d03838b61ada5547d94b91f6df7db07bf1855d37d709c8f08d9ef92ba981e",
          "sha256": "68a8c3e43a33c35f88568423f0fda2736c3dc47205b2a66c35fdd1570f7a9780",
          "sha1": "e849dcf6ef1954750a3d3dc75290e64cf6624d49",
          "md5": "4c01aeb3667373681f2fc9af7c2295f0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "room-testing-2.4.2.aar",
          "url": "room-testing-2.4.2.aar",
          "size": 13623,
          "sha512": "049629bb0a821cb5278a4cfcd66110416f67e9eeeae25315857be33000c2681ee09d03838b61ada5547d94b91f6df7db07bf1855d37d709c8f08d9ef92ba981e",
          "sha256": "68a8c3e43a33c35f88568423f0fda2736c3dc47205b2a66c35fdd1570f7a9780",
          "sha1": "e849dcf6ef1954750a3d3dc75290e64cf6624d49",
          "md5": "4c01aeb3667373681f2fc9af7c2295f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-testing-2.4.2-sources.jar",
          "url": "room-testing-2.4.2-sources.jar",
          "size": 7114,
          "sha512": "ac3f3a4577a60f01f76b2672a8ae6636a8ee898acd50d9714d4cf15949320d7401917581e98c8c4fe56e9d3aa2e9bf3f67900e990ca1b2137c421b2f23e8d7bb",
          "sha256": "3f9bbf7c7ae08269b75dc11c135174070bc71176b05f8aa9bc6d9cc01e7104b0",
          "sha1": "953bfd30ea4f060c56bd77859dceb9f5577100f8",
          "md5": "35970f76fd8a0b3b432bf96285da8bdb"
        }
      ]
    }
  ]
}
