{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-1.3.0-beta02.aar",
          "url": "runtime-saveable-1.3.0-beta02.aar",
          "size": 1086273,
          "sha512": "9adb7ab6e0df7a2a944a276e482f98054ec031fa465a9dc13a2cbc6911ef7b098b710ce2acc9a87a13a92b86faccc3ec279b537b0b1c6f1b0d265ba627b7ca2b",
          "sha256": "8174458f1f2fbd4a4a47a3cde9539156201e7c2dbd752da38e6a0619f264466b",
          "sha1": "45f64dffbeabd256cf03fa9e85eb959901d6cc9c",
          "md5": "2d9c9ca2af687134aad9c0d6e409f20b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-1.3.0-beta02.aar",
          "url": "runtime-saveable-1.3.0-beta02.aar",
          "size": 1086273,
          "sha512": "9adb7ab6e0df7a2a944a276e482f98054ec031fa465a9dc13a2cbc6911ef7b098b710ce2acc9a87a13a92b86faccc3ec279b537b0b1c6f1b0d265ba627b7ca2b",
          "sha256": "8174458f1f2fbd4a4a47a3cde9539156201e7c2dbd752da38e6a0619f264466b",
          "sha1": "45f64dffbeabd256cf03fa9e85eb959901d6cc9c",
          "md5": "2d9c9ca2af687134aad9c0d6e409f20b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-saveable-1.3.0-beta02-sources.jar",
          "url": "runtime-saveable-1.3.0-beta02-sources.jar",
          "size": 10792,
          "sha512": "2a4fd28cfd1e8bc9572cecab3dcc25560efcbf690e104e3b1e7039bd4d9c3bfc28f96e1d996cc2da2fb846b0f279de63a83d9e801867fa275b164a59645c606f",
          "sha256": "a498d31ee590d7b8b4a31021134e3793d6287a08fc0444c99b80020beea432ae",
          "sha1": "dfdc3070b43a1cb2939cc13498dd40988a8d3d93",
          "md5": "55cf532a33cf4313df6415a1342a26a3"
        }
      ]
    }
  ]
}